### PR TITLE
Return the files listed so far instead of null even in case of archive error in getFileList()

### PR DESCRIPTION
**Pull request by klesun-misc**
This allows to process incomplete RAR files: a partial buffer from stream for example. In my case I have like 50 MiB archive loading slower than 1 MiB/s and being able to continuously list files while archive is still loading would be a really nice user experience.

I don't insist on this change, but if you agree it is useful, it would be cool if it got accepted

If something else is needed for this PR to go through, just let me know, I have no life luckily ^_^

### CODE REVIEW

**Comment by YuJianrong** [comment]
In the new release v1.0.0, the files will not be extracted in one function all.
The files will be returned as an iterator and you can traverse the list by `for of` so partial of the archive can be extracted even some files are broken:
```js
const extracted = [];
try{
  for (const file of files) {
    extracted.push(file.extraction);
  }
} catch (unRarErr) {
  // ...
}
```

**Comment by klesun** [comment]
Hi. If you are still going to implement the iterator, I'd like to share some info I found after few days of struggling.
https://github.com/klesun-misc/node-unrar.js-issue3/commit/cdeb62acb511a0c081e834da5e4976f062c68751

There is this `QOpenMode` parameter that is by default `QOPEN_AUTO` because of which rar lib jumps over all file for integrity check before listing files. When archivce size is 1+ GiB this always results in `READ_ERROR`. I changed the default value from `QOPEN_AUTO` to `QOPEN_NONE` and 1+ GiB archives now open like a charm ^_^

**Comment by YuJianrong** [comment]
> Hi. If you are still going to implement the iterator, I'd like to share some info I found after few days of struggling.
> [klesun-misc@cdeb62a](https://github.com/klesun-misc/node-unrar.js-issue3/commit/cdeb62acb511a0c081e834da5e4976f062c68751)
> 
> There is this `QOpenMode` parameter that is by default `QOPEN_AUTO` because of which rar lib jumps over all file for integrity check before listing files. When archivce size is 1+ GiB this always results in `READ_ERROR`. I changed the default value from `QOPEN_AUTO` to `QOPEN_NONE` and 1+ GiB archives now open like a charm ^_^

Thanks for your comment. The migration is already done, you can try if the big archive is working in the new version. I can add your fix into the repo (by override the  original file) if this is required.

**Comment by klesun** [comment]
Thanks, trying out!

A small offtopic, I tried to run `npm run build:release`, and the output `/esm/` directory holds `index.esm.js` and the rest unbundled files that are imported without `.js` extension:
```
import { ExtractorData } from './js/ExtractorData';
```
Considering I'm not magically resolving them in my web-server code, that results in such errors:
image

**Comment by klesun** [comment]
Oh, sorry, never mind, this `/esm/` is probably intended for node environment, not for browser

**Comment by klesun** [comment]
Hm, not sure I'm doing it right, but now I get the `File read error` even when I try to open a normal rar file of around 100 MiB...

**Comment by YuJianrong** [comment]
> Oh, sorry, never mind, this `/esm/` is probably intended for node environment, not for browser
> 
> Upd.: or is it...

The `/esm/` is ESModule which used for webpack (browser) and the `/dist/` is commonjs module which used for nodejs.


> Hm, not sure I'm doing it right, but now I get the `File read error` even when I try to open a normal rar file of around 100 MiB in the browser (after monkey-patching the missing `.js` extensions in imports and path to `unrar.wasm`)...

I have no chance to test on the large file. Have you tried the demo in `/demo/web`? Is it working for small file but not for bigfile?

**Comment by klesun** [comment]
Yeah, sorry, only now noticed the demo, researching it.

In case you need a big rar file, I can share this guy: ;)
http://kunkka-torrent.online/kunkka_host/handmade/torrent_downloads/DLraw.net-Reincarnation%20Kaben%20vol%2001-12.rar

Will write back once make the demo work.

**Comment by YuJianrong** [comment]
> Yeah, sorry, only now noticed the demo, researching it.
> 
> In case you need a big rar file, I can share this guy: ;)
> http://kunkka-torrent.online/kunkka_host/handmade/torrent_downloads/DLraw.net-Reincarnation%20Kaben%20vol%2001-12.rar
> 
> Will write back once make the demo work.

The file is 800 MB!
Anyway, it's decompressed in the web demo on browser.

You may need to add some waitting function and remove content form the demo:
```diff
--- a/demo/web/src/index.ts
+++ b/demo/web/src/index.ts
@@ -68,9 +68,10 @@ document.querySelector<HTMLDivElement>('#file')?.addEventListener(
         filesDom.appendChild(
           fillTemplate('content', {
             fileName: file.fileHeader.name,
-            content: new TextDecoder('utf-8').decode(file.extraction),
+            content: '',//new TextDecoder('utf-8').decode(file.extraction),
           }),
         );
+        await new Promise<void>(r=>setTimeout(()=>r(), 10));
       }
     } catch (err) {
       if (err instanceof UnrarError) {
```

**Comment by klesun** [comment]
Hi again, thank you very much, I managed to make demo page working.

Yeah, I do experience the `READ_ERROR` when I try to load my large rar file that I cut after first 10 MiB before first file is listed.
image

If I open same file with an archive manager, it gets open ok:
image

And similarly, it opens ok in my patched version of `node-unrar.js` with `QOpenMode` changed from `QOPEN_AUTO` to `QOPEN_NONE`.

Sorry, I was not clear enough, the problem is not in trying to parse large file itself, but in trying to parse an incomplete part of it (like when you want to progressively show the buffer what you downloaded so far during a lengthy http retrieval).

**Comment by klesun** [comment]
Here is the cut file in question:
https://kunkka-torrent.online/kunkka_host/handmade/torrent_downloads/dlraw_huj_10mb.rar

Opens in archive manager, does not open with `node-unrar.js`

**Comment by YuJianrong** [comment]
Got it.

So you are trying to make it works for incomplete file? By change the QOPEN define to bypass the integrity checking of unrar?
I'd not prefer to change this option in the official build, what about fork it and try to recompile for your case?

This version should be easier than the last one to for compilation.

**Comment by klesun** [comment]
Well, I already have such fork ;)
https://github.com/klesun-misc/node-unrar.js-issue3/tree/partial-streaming-support-change-cpp
Though I'd love to get rid of it in favor in the main repo.

Maybe it could be specified by option somehow? I'm not a big emscripten guru, but this `QOPEN` thing seems to be one of "Command Arguments" or something like that...

**Comment by klesun** [comment]
Not that I'm willing to force you to waste your time on that, just wanted to let you know about such a use case.

**Comment by YuJianrong** [comment]
> Yes; Yes; Well, I already have such fork ;)
> https://github.com/klesun-misc/node-unrar.js-issue3/tree/partial-streaming-support-change-cpp
> Though I'd love to get rid of it in favor in the main repo.
> 
> Maybe it could be specified by option somehow? I'm not a big emscripten guru, but this `QOPEN` thing seems to be one of "Command Arguments" or something like that...
> 
> If I get it right, this `cmddata.cpp` can even be specified in the rar archive buffer itself by prepending some special characters...

The cpp code is not working like this. The `QOPEN` is a flag which set by another cpp header and fixed in the building artifacts.

The only way to make it configurable is: copy the file, apply your change, build two different `wasm` files (one with the original file and another with the modified one), and load the different file based on the option.

I'd prefer to keep the changes on the cpp source minimum so I'd not go to that way.

> Not that I'm willing to force you to waste your time on that, just wanted to let you know about such a use case.

Anyway thanks you for investigation on this topic. I believe it will be useful for other users with the same requirements :)

**Comment by klesun** [comment]
Ok, thanks to you as well.

One more small note for history: one nasty thing about this integrity check is that it does not run on any rar file, but only on files with `MHEXTRA_LOCATOR` flag in the extra fields data of the main header, so this issue will only reproduce on _some_ rar files, but not on all of them...

**Pull request closed without merging**
