### PR TITLE
#3 Make emscripten module build and import browserify-friendly

### PR DESCRIPTION
**Pull request by klesun**
Solves the "unrar.RarArchive is not a constructor"

https://github.com/YuJianrong/node-unrar.js/issues/3

### CODE REVIEW

**Comment by klesun** [comment]
See https://stackoverflow.com/a/47528954/2750743

Emscripten has some issues with browserify which are solved by compiling with `MODULARIZE` flag.

**Comment by YuJianrong** [comment]
@klesun Thanks for you PR.
I'm currently working on a big refactory to make it works more smoothly on webpack. Hope it can solve your issue.
It will be released soon.

**Comment by klesun** [comment]
Oh, cool, good luck!

**Comment by YuJianrong** [comment]
This issue solved in the new release 1.0.0

**Pull request closed without merging**
